name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/githubActions.key
          chmod 600 ~/.ssh/githubActions.key
          cat >>~/.ssh/config <<END
          Host deployment_server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/githubActions.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GITHUB_ACTIONS_SSH_USER }}
          SSH_KEY: ${{ secrets.GITHUB_ACTIONS_SSH_KEY }}
          SSH_HOST: ${{ secrets.MOVIEZEN_SSH_HOST }}

      - name: Rebuild Docker Container
        run: ssh deployment_server 'cd /home/alexandre/movieZenFrontend && docker-compose down && docker-compose build --no-cache && docker-compose up -d'
